// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test2', async function() {
    // Test name: test2
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://fansfootballfederation.herokuapp.com/")
    // 2 | setWindowSize | 958x1031 | 
    await driver.manage().window().setRect({ width: 958, height: 1031 })
    // 3 | click | linkText=Teams | 
    await driver.findElement(By.linkText("Teams")).click()
    // 4 | click | css=.col-lg-4:nth-child(1) .view_main | 
    await driver.findElement(By.css(".col-lg-4:nth-child(1) .view_main")).click()
    // 5 | click | css=.col-lg-4:nth-child(2) .view_main | 
    await driver.findElement(By.css(".col-lg-4:nth-child(2) .view_main")).click()
    // 6 | click | css=.col-lg-4:nth-child(1) .read_more | 
    await driver.findElement(By.css(".col-lg-4:nth-child(1) .read_more")).click()
    // 7 | click | linkText=Referees | 
    await driver.findElement(By.linkText("Referees")).click()
    // 8 | click | css=.col-lg-4:nth-child(1) .view_main | 
    await driver.findElement(By.css(".col-lg-4:nth-child(1) .view_main")).click()
    // 9 | click | css=.col-lg-4:nth-child(2) .read_more | 
    await driver.findElement(By.css(".col-lg-4:nth-child(2) .read_more")).click()
    // 10 | click | linkText=Home | 
    await driver.findElement(By.linkText("Home")).click()
    // 11 | click | css=.Sonu\E7lar p | 
    await driver.findElement(By.css(".Sonu\\E7lar p")).click()
    // 12 | click | css=.Sonu\E7lar h2 | 
    await driver.findElement(By.css(".Sonu\\E7lar h2")).click()
    // 13 | click | css=.Sonu\E7lar .read_more | 
    await driver.findElement(By.css(".Sonu\\E7lar .read_more")).click()
    // 14 | click | css=.announcment .read_more | 
    await driver.findElement(By.css(".announcment .read_more")).click()
    // 15 | click | css=.col-md-4:nth-child(2) span | 
    await driver.findElement(By.css(".col-md-4:nth-child(2) span")).click()
    // 16 | click | css=.col-md-4:nth-child(2) h3 | 
    await driver.findElement(By.css(".col-md-4:nth-child(2) h3")).click()
    // 17 | click | css=.col-md-4:nth-child(2) img | 
    await driver.findElement(By.css(".col-md-4:nth-child(2) img")).click()
    // 18 | click | css=.container .col-md-12 h2 | 
    await driver.findElement(By.css(".container .col-md-12 h2")).click()
    // 19 | click | css=.Sonu\E7lar .col-md-6:nth-child(2) | 
    await driver.findElement(By.css(".Sonu\\E7lar .col-md-6:nth-child(2)")).click()
  })
})
